#!/usr/bin/env sh

echo "------ HOOK START - BUILD -------"

docker build --build-arg nodetag=${nodetag} --build-arg osver=${osver} -t ${IMAGE_NAME} -f ${DOCKERFILE_PATH} .

echo "------ HOOK END - BUILD -------"